version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    python -m pip install --user C:\Users\Corinnar\Documents\GitHub\sphinxcontrib-quizdown
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

